services:
  - type: web
    name: adsmood-assets-service
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: B2_APPLICATION_KEY_ID
        value: 005ff4da1ff302a0000000002
      - key: B2_APPLICATION_KEY
        value: K0057A6SzCLovuE8SUjN36SIGAARdXc
      - key: B2_BUCKET_ID
        value: CTVAds
      - key: B2_FILE_URL
        value: https://f005.backblazeb2.com/file/CTVAds
      - key: PORT
        value: 3001
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://adsmood-ctv-ads-2025.onrender.com
    autoDeploy: true
    rootDirectory: assets-service 