services:
  # Frontend (Static Site)
  - type: web
    name: ctv-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.0.0

  # Assets Service
  - type: web
    name: ctv-assets-service
    env: node
    buildCommand: cd assets-service && npm install && npm run build
    startCommand: cd assets-service && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: adsmood_ctv_ya5x
          property: connectionString

  # VAST API Service
  - type: web
    name: ctv-vast-api
    env: node
    buildCommand: cd vast-api-service && npm install && npm run build
    startCommand: cd vast-api-service && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: adsmood_ctv_ya5x
          property: connectionString

databases:
  - name: adsmood_ctv_ya5x
    databaseName: adsmood_ctv_ya5x
    user: adsmood
    plan: free 