services:
  - type: web
    name: CTV_Validado_Adsmood
    env: node
    rootDirectory: assets-service
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: B2_APPLICATION_KEY_ID
        value: 005ff4da1ff302a0000000002
      - key: B2_APPLICATION_KEY
        value: K0057A6SzCLovuE8SUjN36SIGAARdXc
      - key: B2_BUCKET_ID
        value: ef1f24bd7af10fef9350021a
      - key: B2_FILE_URL
        value: https://f005.backblazeb2.com/file/CTVAds
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://assets-service-hm83.onrender.com 